name: go test
on: [push]

env:
  TEST_JSON_KEY: ${{ secrets.TEST_JSON_KEY }}

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.2'
          check-latest: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
